services:
  domain-checker:
    build: .
    container_name: domain-checker
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - ./app/.env
